name: Parallel Processing

on:
  push:
    branches: [ main, production]
  pull_request:
    branches: [ main, production]

jobs:
  Analyse:
    name: Analyse Codebase
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Flutter set-up
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
  test:
    name: Run test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Flutter set-up
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter test
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Flutter set-up
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - run: flutter pub get
      - run: flutter build apk --release
      - name: Uplaod APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk