name: Flutter Analysis

on: [push, pull_request]
jobs:
  Analysis:
    name: Analyse Code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Flutter Code
        uses: actions/checkout@v3
      - name: Flutter Setup
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install Dependencies
        run: flutter pub get
      - name: Run Test
        run: flutter test
      - name: Build APK
        run: flutter build apk --release
      - name: Show APK location
        run: echo "APK built at build/app/outputs/flutter-apk/app-release.apk"